[package]
name = "Virganol"
version = "0.0.1"
description = "Virganol desktop backend"
authors = ["SJRnhqh"]
edition = "2021"

[lib]
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std"] }
directories = "5.0"
nu-ansi-term = "0.50"
parking_lot = "0.12"
portable-pty = "0.8"
prost = "0.13"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ssh2 = { version = "0.9", features = ["vendored-openssl"] }
strum = { version = "0.28", features = ["derive"] }
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-os = "2.3.2"
tauri-plugin-shell = "2"
tauri-plugin-store = "2"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json", "chrono"] }
zeroize = "1"

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { version = "3", features = ["linux-native-sync-persistent", "crypto-rust"] }

[target.'cfg(target_os = "macos")'.dependencies]
keyring = { version = "3", features = ["apple-native"] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3", features = ["windows-native"] }

[build-dependencies]
protoc-bin-vendored = "3.0"
tauri-build = { version = "2", features = [] }
tonic-build = "0.12"
