// apps/desktop/src-tauri/src/core/bot/constants/mod.rs
mod provider;
mod settings;

pub(super) use provider::{
    DEEPSEEK_HEALTH_CHECK_TIMEOUT_SECS, OLLAMA_HEALTH_CHECK_TIMEOUT_SECS,
    PROVIDER_CONFIG_STORE_SCOPES, PROVIDER_CONNECTION_SCOPES, PROVIDER_KEYRING_SERVICE,
    PROVIDER_LIFECYCLE_EMIT_SCOPES, PROVIDER_MANAGER_SCOPES, PROVIDER_SECRET_STORE_SCOPES,
};
pub(super) use settings::{SETTINGS_FILE, SPIRIT_PROVIDERS_KEY};
